### ISSUE TITLE
[BUG] Risk Set 404

### ISSUE THREAD

**Issue by saumyakaran** [yieldscan/yieldscan-backend-api#2]
**Describe the bug**
Getting 404 for risk set endpoint

**To Reproduce**
Ping https://yieldscan-api.onrender.com/api/polkadot/rewards/risk-set-only

**Screenshots**
<img width="1440" alt="Screen Shot 2021-02-16 at 11 35 43 AM" src="https://user-images.githubusercontent.com/40575379/108024783-227e5800-701d-11eb-8d99-6f4e909c455d.png">

**Comment by sahilnanda1995** [comment]
resolved
